### ISSUE TITLE
Advanced authentification

### ISSUE THREAD

**Issue by palourde** [sensu/uchiwa#35]
Support authentification with CAS, AD, etc.

**Comment by palourde** [comment]
For anyone interested, we implemented this feature into the [Sensu Enterprise](http://sensuapp.org/enterprise) dashboard. It might be, at some point in the future, released as an open-source feature into Uchiwa.

**Comment by tavorincon** [comment]
@palourde Any updates on when the LDAP authentication feature will make it into open-source Uchiwa?

**Comment by calebhailey** [comment]
@tavorincon at this time there are no plans to implement LDAP authentication in Uchiwa. LDAP-backed Role-based access controls are available now in [Sensu Enterprise](https://sensuapp.org/enterprise) (see here for docs: https://sensuapp.org/docs/0.19/enterprise-dashboard-configuration#role-based-access-controls-rbac), and Sensu Enterprise now comes with a 14-day risk-free trial if you would like to try it out. 

#monitoringlove

**Comment by UnitedMarsupials** [comment]
Gentlemen? What is the status of this a year later? Is the feature supposed to be in the non-Enterprise Uchiwa by now (0.16.0)? Looking under our uchiwa.example.net/#/info I saw a bunch of LDAP-related settings. I now have them populated to the best of my understanding, but I'm still not asked to login, when I load the dashboard...

We are cheap here and will, probably, use an Apache-proxy if we have to... But if it is supposed to work, I'd rather avoid the proxying... Please, advise. Thanks!

**Comment by Esya** [comment]
We're going to use (oauth2_proxy)[https://github.com/bitly/oauth2_proxy] in the meantime, but would have liked a built-in OAuth in a product as mature as uchiwa (And switching just to Entreprise for Auth seems a bit overkill to be honest)

**Comment by luckymike** [comment]
@Esya I recently implemented `oauth2_proxy` with Uchiwa and ran across similar issues. I believe most of the benefits that basic auth would give you are implemented in uchiwa-web. I'm looking into a theme that will play nicely with `oauth2_proxy`. 

If you're interested in collaborating or providing testing and feedback, please contact me via the email in my profile :)

**Comment by rankink** [comment]
I have created a working environment that auth's via github.com/go-ldap/ldap (https://github.com/go-ldap/ldap).  

I have posted a comment in https://github.com/sensu/uchiwa/issues/295 looking for requests on how to structure the code for a pull request.
