### ISSUE TITLE
Uchiwa not displaying output of checks on client page

### ISSUE THREAD

**Issue by nishlo** [sensu/uchiwa#617]
This occurs for green and red checks. The output column for all clients is empty, however for individual checks of that client, the output is displayed. This used to work in previous versions used.

## Expected Behavior
The Output column on the client page should be populated

## Current Behavior
Curling the Api for a client, you can see each check has an output. But the output isn't displayed on the client page in uchiwa:
curl http://<sensuapi_url>:4567/results/server | jq .
  
[
  {
    "check": {
      "type": "standard",
      "status": 0,
      "output": "CheckHardwareFail OK: Hardware OK\n",
      "handlers": [
        "default",
        "hipchat_monitoring"
      ],
      "command": "/etc/sensu/plugins/check-hardware-fail.rb",
      "interval": 60,
      "subscribers": [
        "os_checks"
      ],
      "name": "hardware_check",
      "issued": 1481820883,
      "executed": 1481820883,
      "duration": 0.12
    },
    "client": "EDITED"
  },
  {
    "check": {
      "type": "standard",
      "status": 0,
      "output": "CheckCPU TOTAL OK: total=4.0 user=3.5 nice=0.0 system=0.5 idle=96.0 iowait=0.0 irq=0.0 softirq=0.0 steal=0.0 guest=0.0\n",
      "duration": 1.115,
      "executed": 1481820345,
      "handlers": [
        "default",
        "hipchat_monitoring"
      ],
      "command": "/etc/sensu/plugins/check-cpu.rb -w 80 -c 90",
      "interval": 600,
      "refresh": 1800,
      "occurrences": 5,
      "subscribers": [
        "os_checks"
      ],
      "name": "check_cpu",
      "issued": 1481820345
    },
    "client": "EDITED"
  },
  {
    "check": {
      "status": 0,
      "output": "sensu.chelapphot008.procs.waiting 0 1481820886\n...",
      "duration": 1.135,
      "type": "metric",
      "handlers": [
        "graphite"
      ],
      "command": "/etc/sensu/plugins/vmstat-metrics.rb --scheme sensu.:::name:::",
      "subscribers": [
        "os_metrics"
      ],
      "interval": 60,
      "name": "vmstat_metrics",
      "issued": 1481820884,
      "executed": 1481820884
    },
    "client": "EDITED"
  },
  {
    "check": {
      "type": "standard",
      "status": 0,
      "output": "CheckRAM OK: 61.87% RAM free\n",
      "handlers": [
        "default",
        "hipchat_monitoring"
      ],
      "command": "/etc/sensu/plugins/check-ram.rb",
      "interval": 60,
      "subscribers": [
        "os_checks"
      ],
      "name": "ram_check",
      "issued": 1481820885,
      "executed": 1481820885,
      "duration": 0.125
    },
    "client": "EDITED
  },
  {
    "check": {
      "type": "standard",
      "status": 0,
      "output": "Keepalive sent from client 9 seconds ago",
      "executed": 1481820917,
      "issued": 1481820917,
      "name": "keepalive",
      "thresholds": {
        "critical": 180,
        "warning": 120
      }
    },
    "client": "EDITED"
  },
  {
    "check": {
      "type": "standard",
      "status": 0,
      "output": "CheckNTP OK: NTP offset by 0.382ms\n",
      "duration": 0.117,
      "handlers": [
        "default",
        "hipchat_monitoring"
      ],
      "command": "/etc/sensu/plugins/check-ntp.rb",
      "interval": 60,
      "occurrences": 10,
      "subscribers": [
        "os_checks"
      ],
      "name": "ntp_check",
      "issued": 1481820885,
      "executed": 1481820885
    },
    "client": "EDITED"
  },
  {
    "check": {
      "type": "standard",
      "status": 0,
      "output": "CheckDisk OK: All disk usage under 85% and inode usage under 85%\n",
      "handlers": [
        "default",
        "hipchat_monitoring"
      ],
      "command": "/etc/sensu/plugins/check-disk-usage.rb",
      "interval": 60,
      "subscribers": [
        "os_checks"
      ],
      "name": "disk_check",
      "issued": 1481820885,
      "executed": 1481820885,
      "duration": 0.148
    },
    "client": "EDITED"

## Your Environment

* Uchiwa version used: uchiwa-0.21.0-1.x86_64
* Sensu version used: sensu-0.26.5-2.x86_64
* Operating System and version (e.g. Ubuntu 14.04): CentOS release 6.8 (Final)

**Comment by nishlo** [comment]
![sensu no output displayed](https://cloud.githubusercontent.com/assets/3797377/21265109/b53353e4-c397-11e6-8811-db5362a600cc.jpg)

**Comment by nishlo** [comment]
![sensu output present on a check](https://cloud.githubusercontent.com/assets/3797377/21265152/f6eeda06-c397-11e6-85c5-f5c95a709216.jpg)

**Comment by jaykumar-jnpr** [comment]
Exactly same issue with my uchiwa installation as well.

**Comment by portertech** [comment]
@palourde PING.

**Comment by palourde** [comment]
Hi @nishlo 

Thank you for reporting this issue. This is highly unexpected since it was specifically fixed in 0.21.0 through https://github.com/sensu/uchiwa/issues/612 and I'm unable to reproduce it. Could you make sure to clear your browser cache and/or try with another browser? Also, try to restart the Uchiwa process just to make sure.

Let me know if you still see this issue afterward.

Thanks

**Comment by jaykumar-jnpr** [comment]
Figured out the issue, local to my browser. No precise/foolproof way to clear cache on OSX + Chrome.  Works fine incognito mode.

**Comment by nishlo** [comment]
Figured it out also thanks to above comments. The docker image being used contained uchiwa version with the bug as mentioned by @palourde 
I had tested after yum updating uchiwa and restarting sensuserver, but browser cache was not cleared, so output was still missing.

**Comment by palourde** [comment]
Thank you for your updates! The upgrade process should be smoother for the next releases (we now explicitly mark the index.html file as not cacheable).
